/**
 * THE single source of truth for "who may do what".
 *
 * Code never checks role names (no `if (role === "doctor")`); it asks for a
 * permission: requirePermission("prescription:create"). To change what a role
 * can do, edit ROLE_PERMISSIONS below — nothing else.
 *
 * The frontend gets an exact copy (frontend/src/lib/permissions.ts) generated by
 * `npm run permissions:export`; a test fails if the two drift apart. The
 * frontend only uses it to hide menus/buttons — the API is the real gatekeeper.
 */

export const ROLES = [
  "super_admin",
  "management",
  "reception",
  "doctor",
  "nurse",
  "lab_technician",
  "pharmacist",
  "accounts",
  "patient",
] as const;
export type Role = (typeof ROLES)[number];

export const PERMISSIONS = {
  // Patients (Phase 3). read_basic = name, code, phone, age; read_full = medical history (EMR)
  "patient:create": "Register new patients",
  "patient:read_basic": "Search patients and see basic details",
  "patient:read_full": "See the full medical record (EMR)",
  // Clinicians normally open only patients who have an appointment with them (object-level rule)
  "emr:read_all": "Open the medical record of ANY patient, not only own patients",
  "patient:update": "Edit patient demographic details",
  // Appointments & queue (Phase 4)
  "appointment:create": "Book appointments",
  "appointment:read": "See appointment lists",
  "appointment:update_status": "Check in, cancel or complete appointments",
  "queue:read": "See queue status",
  "queue:call_next": "Call, recall or send back patients in their OWN queue",
  "queue:manage": "Recall or send back patients in any doctor's queue (front desk)",
  // Clinical (Phases 5–6)
  "vitals:create": "Record vitals",
  "vitals:read": "See vitals",
  "visit:create": "Write consultation notes",
  "visit:read": "Read consultation notes",
  "prescription:create": "Write prescriptions",
  "prescription:read": "Read full prescriptions",
  "prescription:read_medication": "Read only the medication part of prescriptions",
  // Laboratory (Phase 7)
  "lab_order:create": "Order lab tests",
  "lab_order:read": "See lab orders",
  "lab_result:create": "Enter lab results",
  "lab_report:upload": "Upload lab report files",
  "lab_report:verify": "Verify and release lab reports",
  "lab_report:read": "Read lab reports",
  "lab_report:deliver": "Print and hand over verified lab reports",
  "ai_summary:use": "Generate the AI visit summary (a draft to verify, never saved automatically)",
  // Pharmacy (Phase 8)
  "dispense:create": "Dispense medicines",
  "stock:read": "See medicine stock",
  "stock:manage": "Adjust stock, purchases and expiry",
  // Billing (Phase 9)
  "bill:read": "See invoices and payments",
  "bill:collect": "Collect payments",
  "bill:discount": "Give discounts and refunds",
  // Reporting
  "report:finance": "Finance reports",
  "report:operations": "Operational reports and live overview",
  "dashboard:read": "Own role dashboard",
  // Patient assistant (hand-offs to staff)
  "inbox:manage": "Staff inbox: read assistant conversations, take over, reply and resolve",
  "knowledge:manage": "Edit and publish the assistant's knowledge base",
  // Administration
  "user:manage": "Create and manage staff accounts",
  "settings:manage": "Hospital settings",
  "master_data:manage": "Departments, doctors, schedules, services and catalogs",
  "doctor:read": "See departments, doctors, schedules and free slots",
  "audit:read": "Read audit logs",
  "automation:read": "See automation rules, outbox, queue and run log",
  "automation:manage": "Change automation rules, templates and settings; retry or cancel messages",
  // Patient portal (Phase 10) — always limited to the patient's OWN data
  "portal:own_records": "Own appointments, prescriptions and reports",
} as const;
export type Permission = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  // Runs the system. No clinical data by default (least privilege).
  super_admin: [
    "dashboard:read",
    "doctor:read",
    "user:manage",
    "settings:manage",
    "master_data:manage",
    "audit:read",
    "automation:read",
    "automation:manage",
    "report:operations",
    "inbox:manage",
    "knowledge:manage",
  ],
  // Read-only analytics. Cannot edit medical records.
  management: [
    "dashboard:read",
    "report:finance",
    "report:operations",
    "appointment:read",
    "queue:read",
    "bill:read",
    "doctor:read",
    "automation:read",
  ],
  // Front desk: basic patient info only — no diagnosis or prescriptions.
  reception: [
    "dashboard:read",
    "patient:create",
    "patient:read_basic",
    "patient:update",
    "appointment:create",
    "appointment:read",
    "appointment:update_status",
    "queue:read",
    "queue:manage",
    "doctor:read",
    "bill:read",
    "bill:collect",
    "inbox:manage",
    "lab_order:read",
    "lab_report:deliver",
  ],
  // Full EMR of THEIR OWN patients (patients with an appointment with them — checked in the API). No billing.
  doctor: [
    "dashboard:read",
    "patient:read_basic",
    "patient:read_full",
    "appointment:read",
    "queue:read",
    "queue:call_next",
    "doctor:read",
    "vitals:read",
    "visit:create",
    "visit:read",
    "prescription:create",
    "prescription:read",
    "lab_order:create",
    "lab_report:read",
    "ai_summary:use",
  ],
  // Vitals and today's waiting list. No prescriptions.
  nurse: [
    "dashboard:read",
    "patient:read_basic",
    "appointment:read",
    "queue:read",
    "doctor:read",
    "vitals:create",
    "vitals:read",
  ],
  // Results, verification and delivery. Four-eyes rule: the person who entered the
  // results can never verify them (enforced in the lab service; see hospital settings).
  lab_technician: [
    "dashboard:read",
    "patient:read_basic",
    "lab_order:read",
    "lab_result:create",
    "lab_report:upload",
    "lab_report:verify",
    "lab_report:read",
    "lab_report:deliver",
  ],
  // Medication part only. No diagnosis or lab reports.
  pharmacist: [
    "dashboard:read",
    "patient:read_basic",
    "prescription:read_medication",
    "dispense:create",
    "stock:read",
    "stock:manage",
  ],
  // Money only. No medical data.
  accounts: ["dashboard:read", "bill:read", "bill:collect", "bill:discount", "report:finance"],
  // Own data only (portal arrives in Phase 10).
  patient: ["portal:own_records"],
};

export const permissionsForRole = (role: Role): readonly Permission[] => ROLE_PERMISSIONS[role] ?? [];

export const roleHasPermission = (role: Role, permission: Permission): boolean =>
  permissionsForRole(role).includes(permission);
