/* eslint-disable @typescript-eslint/no-explicit-any */
import { Request } from "express";
import QRCode from "qrcode";
import { embeddedFontCss, esc, renderPdf } from "../../../documents/pdf";
import { signDocumentCode, verifyUrl } from "../../../documents/signing";
import { formatRange } from "../../../shared/clinical-rules";
import { ageOn } from "../../../utils/date";
import { recordAudit } from "../../audit/audit.service";
import { getSettings, HospitalSettings } from "../../hospital/settings/settings.service";
import { loadOrderForReport } from "./lab.service";

/** PRINTED LAB REPORT (A4). Only verified reports print; each print is a VIEW audit entry. */

const FLAG_TEXT: Record<string, string> = { low: "L", high: "H", abnormal: "A", critical: "C!" };
const when = (d: Date | null) =>
  d
    ? new Date(d).toLocaleString("en-GB", {
        timeZone: "Asia/Dhaka",
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : "—";

export const buildLabReportHtml = (o: any, hospital: HospitalSettings, qrSvg: string) => {
  const tests = o.tests
    .map(
      (t: any) => `
    <div class="test">
      <h3>${esc(t.name)} <span class="code">${esc(t.code)} · ${esc(t.sampleType)}</span></h3>
      <table>
        <thead><tr><th>Parameter</th><th>Result</th><th>Unit</th><th>Reference range</th></tr></thead>
        <tbody>${t.results
          .map(
            (r: any) => `<tr class="${r.flag && r.flag !== "normal" ? `flag ${r.flag}` : ""}">
              <td>${esc(r.name)}</td>
              <td class="val">${esc(r.value)} ${r.flag && r.flag !== "normal" ? `<b>${esc(FLAG_TEXT[r.flag] ?? "")}</b>` : ""}</td>
              <td>${esc(r.unit)}</td>
              <td>${esc(r.normalText || formatRange(r))}</td></tr>`,
          )
          .join("")}</tbody>
      </table>
      ${t.comment ? `<p class="comment">Comment: ${esc(t.comment)}</p>` : ""}
    </div>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"><style>
${embeddedFontCss()}
*{box-sizing:border-box}
body{font-family:"Hind Siliguri",sans-serif;color:#1f2937;font-size:11pt;margin:0;line-height:1.4}
.head{display:flex;justify-content:space-between;border-bottom:3px solid #0f766e;padding-bottom:8px}
.head h1{margin:0;font-size:18pt;color:#0f766e}
.head p{margin:0;font-size:9.5pt;color:#4b5563}
.title{text-align:right}
.title h2{margin:0;font-size:14pt;letter-spacing:.05em}
.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:3px 16px;padding:8px 0;border-bottom:1px solid #d1d5db;font-size:10pt}
.meta b{font-weight:600}
.test{margin-top:12px;page-break-inside:avoid}
h3{margin:0 0 4px;font-size:11.5pt;color:#0f766e}
.code{font-weight:400;color:#6b7280;font-size:9pt}
table{width:100%;border-collapse:collapse;font-size:10.5pt}
th{text-align:left;font-weight:600;border-bottom:1px solid #9ca3af;padding:3px 6px;font-size:9.5pt;color:#374151}
td{border-bottom:1px solid #e5e7eb;padding:3px 6px}
.val{font-weight:600}
tr.flag .val{color:#b45309}
tr.flag.critical .val{color:#b91c1c}
.comment{margin:4px 0 0;font-size:10pt}
.legend{margin-top:10px;font-size:8.5pt;color:#6b7280}
.foot{display:flex;justify-content:space-between;align-items:flex-end;border-top:1px solid #d1d5db;margin-top:18px;padding-top:8px;font-size:9pt;color:#6b7280;page-break-inside:avoid}
.qr{display:flex;gap:8px;align-items:center}
.qr svg{width:64px;height:64px}
.sign{text-align:center;min-width:50mm}
.sign .line{border-top:1px solid #6b7280;margin-bottom:2px}
</style></head><body>
<div class="head">
  <div><h1>${esc(hospital.name)}</h1><p>${esc(hospital.nameBn)}</p><p>${esc(hospital.address)}</p></div>
  <div class="title"><h2>LABORATORY REPORT</h2><p>${esc(o.orderNo)}</p></div>
</div>
<div class="meta">
  <span><b>Patient:</b> ${esc(o.patient.name)}</span>
  <span><b>Age / Sex:</b> ${esc(`${ageOn(o.patient.dateOfBirth, o.date)} y / ${o.patient.gender}`)}</span>
  <span><b>ID:</b> ${esc(o.patient.patientCode)}</span>
  <span><b>Referred by:</b> ${esc(o.doctor ? `${o.doctor.title ?? ""} ${o.doctor.name}`.trim() : "Self")}</span>
  <span><b>Collected:</b> ${esc(when(o.sampleCollectedAt))}</span>
  <span><b>Reported:</b> ${esc(when(o.verifiedAt))}</span>
</div>
${tests}
<p class="legend">H = high · L = low · A = abnormal · C! = critical — please discuss results with your doctor.</p>
<div class="foot">
  <div class="qr">${qrSvg}<div>Scan to verify this report<br><b>${esc(o.orderNo)}</b></div></div>
  <div class="sign"><div class="line"></div>Entered by ${esc(o.resultsEnteredBy?.name ?? "—")}</div>
  <div class="sign"><div class="line"></div>Verified by ${esc(o.verifiedBy?.name ?? "—")}</div>
</div>
<p class="legend" style="text-align:center">Generated by Testolife</p>
</body></html>`;
};

export const labReportPdf = async (req: Request, id: string) => {
  const o = await loadOrderForReport(req, id);
  const qrSvg = await QRCode.toString(verifyUrl(signDocumentCode(o.orderNo)), {
    type: "svg",
    margin: 0,
    errorCorrectionLevel: "M",
  });
  const pdf = await renderPdf(buildLabReportHtml(o.toObject(), await getSettings(), qrSvg));
  await recordAudit({
    req,
    action: "VIEW",
    entityType: "LabOrder",
    entityId: o._id,
    meta: { output: "lab_report_pdf", orderNo: o.orderNo },
  });
  return { pdf, fileName: `${o.orderNo}.pdf` };
};
